name: Benchmarks
on:
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: x64
          show-versioninfo: true
      - uses: julia-actions/julia-buildpkg@v1
      - name: Install dependencies
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.add(["PkgBenchmark", "BenchmarkCI"])
      - name: Run benchmarks
        shell: julia --color=yes {0}
        run: |
          using BenchmarkCI
          BenchmarkCI.judge(; baseline="origin/main", retune=true, verbose=true)
      - name: Print judgement
        shell: julia --color=yes {0}
        run: |
          using BenchmarkCI
          BenchmarkCI.displayjudgement()
      - name: Post results
        shell: julia --color=yes {0}
        run: |
          using BenchmarkCI
          BenchmarkCI.postjudge()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
