name: CompatHelper
on:
  schedule:
    - cron: '0 0 * * *'
  push:
      branches:
        - 'main'
      tags: ['*']
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: x64
          show-versioninfo: true
      - uses: julia-actions/cache@v1
      - name: Pkg.add
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.add("CompatHelper")
      - name: CompatHelper.main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        shell: julia --color=yes {0}
        run: |
          using CompatHelper
          CompatHelper.main(; include_jll = true, subdirs = ["", "docs", "test", "benchmark"])
