name: Formatter
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
    tags: ['*']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
          arch: x64
          show-versioninfo: true
      - uses: julia-actions/cache@v2
      - name: Install JuliaFormatter and format
        shell: julia --color=yes {0}
        run: |
          import Pkg
          Pkg.add("JuliaFormatter")
          import JuliaFormatter
          JuliaFormatter.format(".")
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Format .jl files
          title: 'Automatic JuliaFormatter.jl run'
          branch: auto-juliaformatter-pr
          delete-branch: true
          labels: formatting, automated pr, no changelog
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
